/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package racingCar;

import domain.Car;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Scanner;
import java.util.stream.IntStream;

import static java.util.stream.Collectors.joining;

public class App {
    static final Scanner sc = new Scanner(System.in);
    static ArrayList<Car> cars = new ArrayList<>();
    static int count;
    static int maxDistance = 0;

    public static void init() {
        System.out.println("경주할 자동차 이름을  입력하세요.(이름은 쉼표(,) 기준으로 구분)");
        Arrays.stream(sc.nextLine().split(",")).forEach(name -> {
            cars.add(new Car(name.trim()));
        });
        System.out.println("시도할 횟수는 몇 회인가요?");
        count = sc.nextInt();
    }

    public static void printDistance() {
        cars.forEach(car -> {
            if (car.getPosition() > maxDistance) {
                maxDistance = car.getPosition();
            }
            StringBuilder distance = new StringBuilder();
            IntStream.range(0, car.getPosition()).forEach(i -> {
                distance.append("-");
            });
            System.out.println(car.getName() + " : " + distance);
        });
    }

    public static void printResult() {
        String candidates = cars.stream()
                .filter(car -> car.getPosition() == maxDistance)
                .map(Car::getName)
                .collect(joining(", "));
        System.out.println(candidates + "가 최종 우승했습니다.");
    }

    public static void main(String[] args) {
        init();
        System.out.println("실행결과");
        for (int i = 0; i < count; i++) {
            cars.forEach(Car::Go);
            printDistance();
            System.out.println();
        }
        printResult();
        sc.close();
    }
}
