/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package racingCar;

import domain.Car;

import javax.security.sasl.SaslServer;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Scanner;
import java.util.Spliterator;

public class App {
    static final Scanner sc = new Scanner(System.in);
    static ArrayList<Car> Cars = new ArrayList<>();
    static int count;

    public static void init() {
        System.out.println("경주할 자동차 이름을  입력하세요.(이름은 쉼표(,) 기준으로 구분)");
        Arrays.stream(sc.nextLine().split(",")).forEach(name -> {
            Cars.add(new Car(name.trim()));
        });
        System.out.println("시도할 횟수는 몇 회인가요?");
        count = sc.nextInt();
    }

    public static void main(String[] args) {
        init();
    }
}
